const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const txt=v=>Array.isArray(v)?v.map(txt).join('\n'):typeof v==='object'&&v!==null?Object.values(v).map(txt).filter(Boolean).join('；'):String(v??'');
const media=p=>'/media?path='+encodeURIComponent(p);
const number=v=>v==null?'未记录':Number(v).toLocaleString('zh-CN');
const date=v=>{if(!v)return'时间未记录';const d=new Date(v);return Number.isNaN(+d)?String(v):d.toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})};
const list=a=>`<ul>${(Array.isArray(a)?a:[a]).filter(Boolean).map(x=>`<li>${esc(txt(x))}</li>`).join('')}</ul>`;
const labels={search:'找素材',download:'接入原片',analysis:'拆解与校正',revision:'修改内容',production:'制作首稿',next_cycle:'策略工作记录',growth_data:'整理数据',growth_review:'分析内容',context_review:'核对业务'};
let state={},tab='materials',screen='library',companionOpen=false,contentFilter='all';
const materialComparisons=new Set();let viewPositions={},activeRoute='';
if('scrollRestoration' in history)history.scrollRestoration='manual';
let selectedMaterial=null,selectedTask=null,selectedResult=null,query='',filter='all',editing=false,businessEditing=false,resultEditing=false;
const drafts=new Map();
let loadedProject=null;
let materialView='segments', companionView='reference', compareVersion=null, contentQuery='', businessSourceQuery='', selectedDataChannel=null, metricSort='', sortAscending=false;
const comparedRows=new Set();
const latest=b=>(b?.workbench_versions||[]).at(-1);
const task=()=>state.productions?.find(b=>b.task_id===selectedTask)||state.productions?.at(-1);
const title=b=>latest(b)?.text.split('\n').find(s=>s.trim())?.replace(/^#+\s*/,'').slice(0,110)||state.materials?.find(m=>m.id===b?.workbench_source)?.strategy?.draft_brief||'等待第一版内容';
const queue=()=>state.requests?.filter(r=>r.status==='queued')||[];
const key=k=>'workbench:'+state.project_key+':'+k;
function draft(k){if(drafts.has(k))return drafts.get(k);try{const v=JSON.parse(localStorage.getItem(key(k)));if(v)drafts.set(k,v);return v}catch{return null}}
function cache(k,v){drafts.set(k,v);try{localStorage.setItem(key(k),JSON.stringify(v))}catch{}}
function clearDraft(k){drafts.delete(k);try{localStorage.removeItem(key(k))}catch{}}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),6500)}
async function api(path,body){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','X-Workbench-Token':$('meta[name="workbench-token"]').content},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error||'未能保存');return d.result}
async function guard(fn,button){if(button)button.disabled=true;try{await fn()}catch(e){toast(e.message)}finally{if(button?.isConnected)button.disabled=false}}
function routeParts(){try{return (location.hash.slice(1)||'materials').split('/').map(decodeURIComponent)}catch{return ['materials']}}
function persistBrowse(){cache('browse-v6',{query,filter,contentQuery,contentFilter,dataQuery,dataChannel,metricSort,sortAscending,materialComparisons:[...materialComparisons],comparedRows:[...comparedRows]})}
function rememberView(){if(!activeRoute)return;const video=$('#source-player'),editor=$('#content-text');viewPositions[activeRoute]={y:scrollY,videoTime:video?.currentTime,editorScroll:editor?.scrollTop,selectionStart:editor?.selectionStart,selectionEnd:editor?.selectionEnd};cache('positions-v6',viewPositions);persistBrowse()}
function restoreView(){const pos=viewPositions[activeRoute];if(!pos){window.scrollTo(0,0);return}requestAnimationFrame(()=>{window.scrollTo(0,pos.y||0);const editor=$('#content-text');if(editor){editor.scrollTop=pos.editorScroll||0;if(pos.selectionStart!=null)editor.setSelectionRange(pos.selectionStart,pos.selectionEnd)}const video=$('#source-player');if(video&&pos.videoTime!=null){const seek=()=>{video.currentTime=Math.min(pos.videoTime,Number.isFinite(video.duration)?Math.max(0,video.duration-.05):pos.videoTime)};if(video.readyState)seek();else video.addEventListener('loadedmetadata',seek,{once:true})}})}
function applyRoute(restore=true){const parts=routeParts();tab=['materials','content','results','business'].includes(parts[0])?parts[0]:'materials';screen='library';if(tab==='materials'){if(parts[1]==='compare')screen='compare';else if(parts[1]){screen='detail';selectedMaterial=parts[1]}}else if(tab==='content'&&parts[1]){screen='editor';selectedTask=parts[1]}else if(tab==='results'){if(parts[1]==='item'){screen='detail';selectedDataChannel=parts[2];selectedResult=parts[3]}else if(parts[1]==='report'){screen='report';selectedReview=parts[2]}else if(parts[1]==='reports')screen='reports';else if(parts[1]==='compare')screen='compare'}activeRoute=location.hash.slice(1)||'materials';draw();if(restore)restoreView()}
function navigate(route){rememberView();closeDialog();const parts=route.split('/');if(parts[0]==='content'&&route!==activeRoute)companionOpen=false;history.pushState(null,'','#'+route);applyRoute()}
async function refresh(){rememberView();const r=await fetch('/api/state');if(!r.ok)throw Error('暂时读不到项目，请重新打开工作台');state=await r.json();if(loadedProject!==state.project_key){loadedProject=state.project_key;const saved=draft('browse-v6')||{};query=saved.query||'';filter=saved.filter||'all';contentQuery=saved.contentQuery||'';contentFilter=saved.contentFilter||'all';dataQuery=saved.dataQuery||'';dataChannel=saved.dataChannel||'all';metricSort=saved.metricSort||'';sortAscending=!!saved.sortAscending;materialComparisons.clear();(saved.materialComparisons||[]).forEach(x=>materialComparisons.add(x));comparedRows.clear();(saved.comparedRows||[]).forEach(x=>comparedRows.add(x));viewPositions=draft('positions-v6')||{}}applyRoute()}
function activate(name){navigate(name)}
function goTask(id){navigate('content/'+encodeURIComponent(id))}
function backButton(route,label){return `<div class="view-back"><button class="quiet" data-route="${esc(route)}">← ${label}</button></div>`}
function missingObject(route,label){return backButton(route,label)+'<div class="empty"><h2>这条记录暂时找不到</h2><p>可以返回列表重新选择，原有资料没有被删除。</p></div>'}
function sourceKind(m){return {public_content_only:'公开内容',third_party_ad_library:'供应商投放素材',commercial_like_proxy:'推广场景线索',user_supplied_unverified:'自行导入',verified_paid_owned_account:'自有投放记录'}[m.source_kind]||'来源待核对'}
function related(m){return state.productions?.find(b=>b.workbench_source===m.id&&(!state.context_revision||b.context_revision===state.context_revision))}
function awaitingContext(){return queue().some(r=>r.kind==='context_review')}
function statusOf(b){const v=latest(b);if(!v)return'等待首稿';return v.adopted?'已采用':'待查看'}
function showDialog(html){$('#detail-body').innerHTML=html;if(!$('#detail').open)$('#detail').showModal()}
function closeDialog(){$('#detail').close()}
function contextLine(){const c=state.context||{};return `<div class="business-line"><span><b>业务目标</b> ${esc(txt(c.business_goal)||'先让 AI 了解你的工作')}</span><button class="text-button" data-tab="business">查看业务理解</button></div>`}
function draw(){
 $('#company').textContent=state.context?.name||'我的业务';$('#material-count').textContent=state.materials?.length||0;$('#content-count').textContent=state.productions?.length||0;
 $('#sample-note').hidden=!state.history_sample;
 $$('nav button').forEach(b=>{b.classList.toggle('active',b.dataset.tab===tab);if(b.dataset.tab===tab)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});
 $('#page-title').textContent={materials:'素材与拆解',content:'我的内容',results:'数据与复盘',business:'我的业务'}[tab];
 $('#next-step').innerHTML='';$('#next-step').hidden=true;
 $('#requests-button').textContent=queue().length?`待处理 ${queue().length}`:'处理记录';
 ({materials:renderMaterials,content:renderContent,results:renderResults,business:renderBusiness}[tab])();
 cache('selection',{task:selectedTask,material:selectedMaterial,result:selectedResult});
}
function pendingLine(requests){if(!requests.length)return'';return `<div class="request-line"><span>${requests.length} 项要求已保存，等待 AI 接续</span><button class="text-button" data-action="requests">查看并继续</button></div>`}
function materialCard(m){return `<article class="library-card"><button class="material-open" data-material="${esc(m.id)}"><div class="library-cover">${m.frames?.[0]?`<img src="${media(m.frames[0].path)}" alt="${esc(m.title)}的视频画面" loading="lazy">`:'<span class="cover-empty">视频画面待接入</span>'}<span class="cover-source">${sourceKind(m)}</span><span class="cover-play" aria-hidden="true">▶</span></div><div class="library-card-body"><p class="object-meta">${esc(m.author)}</p><h2>${esc(m.title)}</h2><div class="library-status"><span class="status-pill ${m.adoptable?'positive':''}">${m.adoptable?'可借鉴':'待核对'}</span><span>${m.reviewed?'已拆解':'待拆解'}</span></div></div></button><div class="card-bottom"><div class="card-metrics"><span>赞 <b>${number(m.organic_metrics?.likes)}</b></span><span>评论 <b>${number(m.organic_metrics?.comments)}</b></span></div><label class="compare-label"><input type="checkbox" data-material-compare="${esc(m.id)}" ${materialComparisons.has(m.id)?'checked':''}> 对比</label></div></article>`}
function renderMaterials(){
 const all=state.materials||[];
 if(screen==='compare'){renderMaterialComparison();return}
 if(screen==='detail'){const m=all.find(x=>x.id===selectedMaterial);$('#workspace').innerHTML=m?`${backButton('materials','返回素材库')}<section id="material-detail" class="material-detail">${detailHTML(m)}</section>`:missingObject('materials','返回素材库');bindMaterial();return}
 const visible=all.filter(m=>(filter==='all'||filter==='ready'&&m.adoptable||filter==='review'&&!m.adoptable)&&[m.title,m.author,txt(m.strategy),txt(m.interpretations)].join(' ').toLowerCase().includes(query.toLowerCase()));
 $('#workspace').innerHTML=`<div class="library-intro"><div><h2>参考素材库 <small>${all.length} 条</small></h2><p>先浏览、筛选，找到值得深入看的一条。</p></div><div class="actions"><button class="quiet" data-action="add-video">导入视频</button><button class="primary" data-action="new-search">搜索新素材</button><input id="video-file" type="file" accept="video/mp4,video/quicktime,video/webm,.m4v" hidden aria-label="添加视频"></div></div>${pendingLine(queue().filter(r=>['search','download','analysis'].includes(r.kind)))}
 <div class="library-toolbar"><label class="sr-only" for="search">搜索素材</label><input id="search" value="${esc(query)}" placeholder="搜索标题、作者或借鉴点"><div class="filter-tabs">${[['all','全部'],['ready','可借鉴'],['review','待核对']].map(([v,l])=>`<button data-filter="${v}" aria-pressed="${filter===v}">${l}</button>`).join('')}</div><div class="compare-control"><span>${materialComparisons.size?'已选 '+materialComparisons.size+' 条':'可选择两条对比'}</span><button class="quiet" data-route="materials/compare" ${materialComparisons.size!==2?'disabled':''}>对比素材</button>${materialComparisons.size?'<button class="text-button" data-action="clear-material-compare">清空</button>':''}</div></div>
 <div class="material-library">${visible.map(materialCard).join('')||'<div class="empty"><h2>没有匹配的素材</h2><p>试试其他关键词，或导入手边的视频。</p></div>'}</div>`;
 $('#search').oninput=e=>{query=e.target.value;persistBrowse();const pos=e.target.selectionStart;renderMaterials();$('#search').focus();$('#search').setSelectionRange(pos,pos)};
 $$('[data-material-compare]').forEach(input=>input.onchange=e=>{if(e.target.checked){if(materialComparisons.size>=2){e.target.checked=false;toast('先对比两条，可取消一条再换选。');return}materialComparisons.add(e.target.dataset.materialCompare)}else materialComparisons.delete(e.target.dataset.materialCompare);persistBrowse();const y=scrollY;renderMaterials();window.scrollTo(0,y)});
}
function renderMaterialComparison(){const rows=(state.materials||[]).filter(m=>materialComparisons.has(m.id));$('#workspace').innerHTML=backButton('materials','返回素材库')+(rows.length===2?`<div class="comparison-heading"><h2>对照这两条素材</h2><p>比较开头、表达和借鉴点。公开互动只作参考，不代表自己的投放结果。</p></div><div class="material-comparison">${rows.map(m=>`<article><h2>${esc(m.title)}</h2><p class="object-meta">${esc(m.author)} · ${sourceKind(m)}</p>${m.video?`<video controls preload="metadata" ${m.frames?.[0]?`poster="${media(m.frames[0].path)}"`:''} src="${media(m.video)}"></video>`:'<p class="empty-small">原片未接入</p>'}<h3>开头怎么讲</h3><p>${esc(m.whitebox?.timeline?.[0]?.spoken_message||'尚未记录')}</p><h3>表达逻辑</h3><p>${esc(m.whitebox?.one_sentence_logic||'尚未拆解')}</p><h3>可以借什么</h3>${list(m.whitebox?.transfer_reasoning?.keep||m.strategy?.borrow_mechanism)}<h3>要换成自己的</h3>${list(m.whitebox?.transfer_reasoning?.replace||m.strategy?.do_not_copy)}<button class="quiet" data-material="${esc(m.id)}">查看完整拆解</button></article>`).join('')}</div>`:'<div class="empty"><h2>先在素材库选择两条</h2><p>选定后再进入对比。</p></div>')}
function secondsAt(value){const t=String(value??'').trim().match(/\d+(?:\.\d+)?(?::\d+(?:\.\d+)?)?/);if(!t)return null;const a=t[0].split(':').map(Number);return a.length===2?a[0]*60+a[1]:a[0]}
function materialPane(m){
 const w=m.whitebox||{},s=m.strategy||{},r=w.reconstruction||{};
 if(materialView==='segments')return `<p class="panel-hint">点击时间定位原片。以下为已保存的画面与表达摘录，不是完整逐字稿。</p><div class="segment-list">${(w.timeline||[]).map((t,i)=>`<article class="segment" data-segment="${i}"><div class="segment-heading"><button class="time-button" data-seek="${secondsAt(t.time)??0}" ${!m.video?'disabled':''} aria-label="定位原片 ${esc(t.time)}">${esc(t.time)} <span aria-hidden="true">▶</span></button><h3>${esc(t.stage)}</h3></div><p class="spoken-excerpt">${esc(t.spoken_message||'这一段尚未记录表达')}</p><p class="visual-note"><b>画面</b>${esc(t.visual)}</p><p class="analysis-note"><b>拆解</b>${esc(t.how_they_work_together||t.why_it_matters)}</p>${t.evidence?`<small class="evidence-note">依据：${esc(t.evidence)}</small>`:''}</article>`).join('')||'<div class="empty-small"><h3>还没有分段拆解</h3><p>可在下方说明重点，请 AI 结合原片补充。</p></div>'}</div>`;
 if(materialView==='judgment')return `<div class="judgment-copy">${!m.adoptable?`<p class="notice">${esc((m.hold_reasons||[]).join('；')||'还需要核对业务适配。')}</p>`:''}<h3>这条素材的表达逻辑</h3><p>${esc(w.one_sentence_logic||s.borrow_mechanism||'待拆解')}</p><h3>这条素材为什么值得看</h3><p>${esc(w.transfer_reasoning?.reason||s.context_fit_reason||'还需要结合业务资料核对。')}</p><h3>可以借鉴</h3>${list(w.transfer_reasoning?.keep||s.borrow_mechanism)}<h3>需要换成自己的</h3>${list(w.transfer_reasoning?.replace||s.do_not_copy)}${(w.persuasion_chain||[]).length?`<h3>它怎样说服观众</h3>${list(w.persuasion_chain.map(x=>x.question+' '+x.answer))}`:''}${(w.claims_to_check||[]).length?`<h3>使用前需要核实</h3>${list(w.claims_to_check.map(x=>x.source_says+' → '+x.needed_before_use))}`:''}${r.shots?.length?`<details><summary>已有改编镜头建议</summary><p>${esc(r.goal)}</p>${r.shots.map(x=>`<p><b>${esc(x.time)} · ${esc(x.job)}</b><br>${esc(x.visual)}<br>${esc(x.text)}</p>`).join('')}${list(r.owner_questions)}</details>`:''}</div>`;
 return `<div class="source-facts"><h3>来源信息</h3><dl><div><dt>原始标题 / 入库名称</dt><dd>${esc(m.title)}</dd></div><div><dt>作者</dt><dd>${esc(m.author||'未记录')}</dd></div><div><dt>来源类型</dt><dd>${sourceKind(m)}</dd></div><div><dt>保存时间</dt><dd>${date(m.collected_at)}</dd></div></dl><h3>公开互动</h3>${metricBox(m.organic_metrics)}${Object.keys(m.paid_metrics||{}).length?`<h3>供应商投放字段</h3>${metricBox(m.paid_metrics)}`:''}<p class="panel-hint">公开互动、供应商线索与自己的投放成绩分开看。未记录的数据不表示零。</p></div>`;
}
function previewFrames(m){const frames=m.frames||[];if(frames.length<=8)return frames;const chosen=[];for(let i=0;i<8;i++)chosen.push(frames[Math.round(i*(frames.length-1)/7)]);return chosen}
function detailHTML(m){
 const b=related(m),blocked=awaitingContext();
 return `<div class="object-heading"><div><p class="object-meta">${esc(m.author)} · ${sourceKind(m)}</p><h2>${esc(m.title)}</h2></div>${b?`<button class="quiet" data-task="${esc(b.task_id)}">打开相关内容 ↗</button>`:m.adoptable&&!blocked?`<button class="secondary" data-start="${esc(m.id)}">用它做内容</button>`:'<span class="muted">适配待核对</span>'}</div>
 <div class="analysis-workspace"><section class="source-station" aria-label="原片与关键画面"><div class="source-video">${m.video?`<video id="source-player" controls preload="metadata" ${m.frames?.[0]?`poster="${media(m.frames[0].path)}"`:''} src="${media(m.video)}"></video>`:'<div class="empty-small">原片尚未接入</div>'}</div><div class="media-caption"><b>参考原片</b>${m.source_url?`<a href="${esc(m.source_url)}" target="_blank" rel="noopener noreferrer">原始来源 ↗</a>`:''}</div>${m.frames?.length?`<div class="shot-picker" aria-label="关键画面定位">${previewFrames(m).map(f=>`<button data-seek="${secondsAt(f.time)??0}" ${!m.video?'disabled':''} aria-label="定位 ${esc(f.time)} 秒"><img loading="lazy" src="${media(f.path)}" alt="${esc(f.time)} 秒关键画面"><span>${esc(f.time)}s</span></button>`).join('')}</div>`:''}</section>
 <section class="analysis-station" aria-label="原片分析"><div class="work-tabs" aria-label="素材查看方式">${[['segments','分段拆解'],['judgment','借鉴判断'],['source','素材信息']].map(([k,l])=>`<button data-material-view="${k}" aria-pressed="${materialView===k}">${l}</button>`).join('')}</div><div id="analysis-pane" class="analysis-pane">${materialPane(m)}</div><div class="inline-ai"><label for="analysis-message">补充事实，或让 AI 重看一处</label><form id="analysis-form"><textarea id="analysis-message" rows="2" placeholder="例如：重点看看开头 3 秒，画面和口播是怎么配合的。">${esc(draft('analysis:'+m.id)?.text||'')}</textarea><div class="inline-ai-actions"><small>提交后等待当前 AI 对话处理</small><button class="quiet">提交给 AI</button></div></form></div></section></div>`;
}
function bindMaterial(){
 const m=state.materials?.find(x=>x.id===selectedMaterial);if(!m)return;
 const video=$('#source-player');if(video)video.ontimeupdate=()=>{const times=(m.whitebox?.timeline||[]).map(t=>secondsAt(t.time)??0);let index=-1;times.forEach((t,i)=>{if(video.currentTime>=t)index=i});$$('[data-segment]').forEach(el=>{const active=Number(el.dataset.segment)===index;el.classList.toggle('is-current',active);el.querySelector('.time-button')?.setAttribute('aria-current',String(active))})};
 const f=$('#analysis-form');if(f){$('#analysis-message').oninput=e=>cache('analysis:'+m.id,{text:e.target.value});f.onsubmit=e=>{e.preventDefault();guard(async()=>{const message=$('#analysis-message').value.trim();if(!message)throw Error('请先写下要核对的地方');await api('/api/request',{kind:'analysis',material_id:m.id,message});clearDraft('analysis:'+m.id);await refresh();toast('要求已保存，等待当前 AI 对话处理。可从“处理记录”接续。')},e.submitter)}}
}

function taskOptions(bundles){return `<label class="sr-only" for="task-select">当前内容任务</label><select id="task-select">${bundles.map(b=>`<option value="${esc(b.task_id)}" ${b.task_id===selectedTask?'selected':''}>${esc(title(b))} · ${statusOf(b)}</option>`).join('')}</select>`}
function companionHTML(b){
 const versions=b.workbench_versions||[],source=state.materials.find(m=>m.id===b.workbench_source);
 const tabs=`<div class="companion-return"><button class="quiet" data-action="close-companion">收起并回到正文 ↑</button></div><div class="work-tabs">${[['reference','参考拆解'],['versions','历史版本'],['brief','内容要求']].map(([k,l])=>`<button data-companion="${k}" aria-pressed="${companionView===k}">${l}</button>`).join('')}</div>`;
 if(companionView==='versions'){
 const pendingDraft=draft('content:'+b.task_id),conflict=pendingDraft&&pendingDraft.text!==latest(b)?.text&&pendingDraft.base_version!==latest(b)?.version_id;const old=(conflict?versions:versions.slice(0,-1)).slice().reverse(),chosen=old.find(v=>v.version_id===compareVersion)||old[0];compareVersion=chosen?.version_id||null;
 return tabs+(chosen?`<div class="companion-body"><label for="compare-version">对照哪一版</label><select id="compare-version">${old.map(v=>`<option value="${esc(v.version_id)}" ${v===chosen?'selected':''}>${esc(v.version_id)} · ${v.adopted?'曾采用':'未采用'} · ${date(v.created_at)}</option>`).join('')}</select><p class="panel-hint">左边为当前正文，右边为所选版本原文。</p><div class="version-comparison document-body">${esc(chosen.text)}</div>${chosen.adopted?`<button class="text-button" data-result="${esc(b.task_id+':'+chosen.version_id)}">查看这一版的使用记录</button>`:''}</div>`:'<div class="empty-small"><h3>目前只有这一版</h3><p>正文修改保存后，旧版会留在这里，可以并排对照。</p></div>');
 }
 if(companionView==='brief')return tabs+`<div class="companion-body"><h3>写给谁</h3><p>${esc(txt(b.locked_strategy?.target_audience)||'待核对')}</p><h3>客户在什么场景</h3><p>${esc(txt(b.locked_strategy?.customer_scene)||'待核对')}</p><h3>希望他做什么</h3><p>${esc(txt(b.locked_strategy?.desired_action)||'待核对')}</p><h3>表达边界</h3>${list(b.locked_strategy?.expression_boundaries)}</div>`;
 return tabs+(source?`<div class="companion-body reference-companion"><p class="object-meta">${esc(source.author)} · 参考素材</p><h3>${esc(source.title)}</h3>${source.video?`<video controls preload="metadata" ${source.frames?.[0]?`poster="${media(source.frames[0].path)}"`:''} src="${media(source.video)}"></video>`:''}<h3>可借的方法</h3>${list(source.whitebox?.transfer_reasoning?.keep||source.strategy?.borrow_mechanism)}<h3>要换成自己的</h3>${list(source.whitebox?.transfer_reasoning?.replace||source.strategy?.do_not_copy)}<details open><summary>分段表达参考</summary>${(source.whitebox?.timeline||[]).map(t=>`<p><b>${esc(t.time)} · ${esc(t.stage)}</b><br>${esc(t.spoken_message)}</p>`).join('')}</details><button class="text-button" data-source="${esc(source.id)}">打开完整素材与拆解 ↗</button></div>`:'<div class="empty-small"><p>这份内容没有关联的参考素材。已有正文仍可直接修改和保存。</p></div>');
}
function bindCompanion(){if($('#compare-version'))$('#compare-version').onchange=e=>{compareVersion=e.target.value;$('#content-companion').innerHTML=companionHTML(task());bindCompanion()}}
function renderContent(){
 if(screen==='editor'){if(!(state.productions||[]).some(b=>b.task_id===selectedTask)){$('#workspace').innerHTML=missingObject('content','返回我的内容');return}renderContentEditor();return}
 const all=state.productions||[],rows=all.filter(b=>title(b).toLowerCase().includes(contentQuery.toLowerCase())&&(contentFilter==='all'||contentFilter==='adopted'&&latest(b)?.adopted||contentFilter==='draft'&&!latest(b)?.adopted));
 $('#workspace').innerHTML=`<div class="library-intro"><div><h2>我的内容库 <small>${all.length} 份</small></h2><p>查找已有作品，选一份继续修改或查看版本。</p></div><button class="quiet" data-action="content-help">整理已有内容</button></div><div class="library-toolbar"><label class="sr-only" for="content-search">查找内容</label><input id="content-search" value="${esc(contentQuery)}" placeholder="搜索内容标题"><div class="filter-tabs">${[['all','全部'],['draft','待查看'],['adopted','已采用']].map(([k,l])=>`<button data-content-filter="${k}" aria-pressed="${contentFilter===k}">${l}</button>`).join('')}</div></div><div class="content-library">${rows.map(b=>{const v=latest(b),saved=draft('content:'+b.task_id),source=state.materials.find(m=>m.id===b.workbench_source);return `<button class="content-library-item" data-task="${esc(b.task_id)}"><div class="content-item-main"><p class="object-meta">${v?'内容稿件':'等待首稿'}${saved&&saved.text!==v?.text?' · 有未保存修改':''}</p><h2>${esc(title(b))}</h2><p class="content-excerpt">${esc(v?.text.split('\n').slice(1).filter(Boolean).join(' ')||'已有制作要求，等待 AI 接续。')}</p><small>${source?'参考：'+esc(source.title):'独立内容'}</small></div><div class="content-item-meta"><span class="status-pill ${v?.adopted?'positive':''}">${statusOf(b)}</span><span>${b.workbench_versions?.length||0} 个版本</span><span>${date(v?.created_at||b.created_at)}</span><b>打开内容 →</b></div></button>`}).join('')||'<div class="empty"><h2>这里还没有匹配内容</h2><p>可以调整筛选，或把已有稿件交给 AI 整理。</p><button class="quiet" data-tab="materials">去素材库看看</button></div>'}</div>`;
 $('#content-search').oninput=e=>{contentQuery=e.target.value;persistBrowse();const pos=e.target.selectionStart;renderContent();$('#content-search').focus();$('#content-search').setSelectionRange(pos,pos)};
}
function toggleCompanion(view,open=true){const editor=$('#content-text');if(!editor)return;companionOpen=open;companionView=view||companionView;$('.writing-columns').classList.toggle('with-companion',open);$('#content-companion').hidden=!open;$('#content-companion').innerHTML=open?companionHTML(task()):'';$('[data-action="close-companion"]').hidden=!open;$$('[data-toggle-companion]').forEach(b=>b.setAttribute('aria-pressed',String(open&&b.dataset.toggleCompanion===companionView)));bindCompanion();if(matchMedia('(max-width:950px)').matches){if(open)$('#content-companion').scrollIntoView({block:'start'});else{editor.scrollIntoView({block:'center'});editor.focus({preventScroll:true})}}}
function renderContentEditor(){
 const bundles=state.productions||[];if(!bundles.length){$('#workspace').innerHTML='<div class="empty"><h2>这里收纳你的内容和版本</h2><p>把已有内容交给 AI 整理，或在素材区选择参考来制作内容。</p><div class="actions"><button class="secondary" data-action="content-help">整理已有内容</button><button class="quiet" data-tab="materials">查看素材</button></div></div>';return}
 const b=task();selectedTask=b.task_id;const v=latest(b),versions=b.workbench_versions||[],savedDraft=draft('content:'+b.task_id),stale=state.context_revision&&b.context_revision!==state.context_revision;
 const sameDraft=!!savedDraft&&savedDraft.text!==(v?.text||''),conflict=!!sameDraft&&savedDraft.base_version!==(v?.version_id??null),visible=bundles.filter(x=>title(x).toLowerCase().includes(contentQuery.toLowerCase()));
 $('#workspace').innerHTML=`${backButton('content','返回我的内容')}${pendingLine(queue().filter(r=>r.task_id===b.task_id))}<div class="content-desk">
 <section class="writing-desk"><div class="object-heading"><div><p class="object-meta">${v?`${esc(v.version_id)} · ${v.adopted?'已采用':'未采用'} · ${date(v.created_at)}`:'尚无首稿'}</p><h2>${esc(title(b))}</h2></div><button class="quiet" data-copy-content="${esc(b.task_id)}">复制正文</button></div>${stale?'<div class="notice">这份内容属于更新前的业务，仅供回看。请先重新核对方向。</div>':''}
 ${conflict?`<div class="draft-conflict"><p>你的草稿基于 ${esc(savedDraft.base_version||'首稿')}，已有更新的 ${esc(v?.version_id)}。先对照，再决定如何继续；已保存版本都会保留。</p><div><button class="quiet" data-action="compare-latest">对照最新版</button><button class="quiet" data-action="rebase-draft">以 ${esc(v?.version_id)} 为基线保留我的草稿</button></div></div>`:''}<div class="editor-view-tools"><span>${esc(txt(b.locked_strategy?.target_audience)||'内容编辑')}</span><div><button class="quiet" data-toggle-companion="reference">查看参考</button><button class="quiet" data-toggle-companion="versions">对照旧版</button><button class="quiet" data-toggle-companion="brief">内容要求</button><button class="text-button" data-action="close-companion" ${!companionOpen?'hidden':''}>收起对照</button></div></div><div class="writing-columns ${companionOpen?'with-companion':''}"><article class="writing-paper"><div class="editor-toolbar"><span>当前正文 <small>${v?esc(v.version_id):'首稿'}</small></span><div><button class="primary" id="save-version" ${stale||conflict||!sameDraft?'disabled':''}>保存${v?'新版本':'首稿'}</button>${v?`<button class="quiet" id="adopt-version" ${sameDraft||stale||v.adopted?'disabled':''}>${v.adopted?'已采用':`采用 ${esc(v.version_id)}`}</button>`:''}</div></div>
 <label for="content-text" class="sr-only">修改正文</label><textarea id="content-text" class="content-text" ${stale?'readonly':''} placeholder="把已有稿件放在这里，或请 AI 根据参考制作首稿。">${esc(savedDraft?.text??v?.text??'')}</textarea><div class="draft-bar"><span id="draft-status" role="status">${sameDraft?'有未保存修改，尚未形成版本。':'正文可直接修改；已保存的版本会保留。'}</span><button class="text-button" data-action="discard-draft" ${!sameDraft?'hidden':''}>放弃草稿</button></div>
 <div class="inline-ai"><form id="content-ai-form"><label for="content-ai-message">让 AI 帮你改</label><textarea id="content-ai-message" rows="2" placeholder="例如：开头保留，帮我把中间的解释改得更口语化。">${esc(draft('revision:'+b.task_id)?.text||'')}</textarea><div class="inline-ai-actions"><small>${sameDraft?'请先保存正文，AI 才能基于这份修改继续。':'AI 按已保存版本修改，完成后保留旧版。'}</small><button class="quiet" id="ask-revision" ${stale||sameDraft?'disabled':''}>${v?'提交修改要求':'请 AI 制作首稿'}</button></div></form></div>${v?.adopted?`<button class="text-button result-entry" data-result="${esc(b.task_id+':'+v.version_id)}">查看这一版的使用记录 ↗</button>`:''}</article>
 <section id="content-companion" class="content-companion" aria-label="写作对照资料" ${!companionOpen?'hidden':''}>${companionOpen?companionHTML(b):''}</section></div></section></div>`;
 $('#content-text').oninput=e=>{const dirty=e.target.value!==(v?.text||'');cache('content:'+b.task_id,{text:e.target.value,base_version:savedDraft?savedDraft.base_version:(v?.version_id??null)});$('#draft-status').textContent=dirty?'修改已暂存在当前浏览器，尚未保存为新版本。':'正文与已保存版本一致。';$('#save-version').disabled=stale||conflict||!dirty;if($('#adopt-version'))$('#adopt-version').disabled=stale||dirty||v.adopted;$('#ask-revision').disabled=stale||dirty;$('[data-action="discard-draft"]').hidden=!dirty;$('#content-ai-form small').textContent=dirty?'请先保存正文，AI 才能基于这份修改继续。':'AI 按已保存版本修改，完成后保留旧版。'};
 $('#save-version').onclick=e=>guard(async()=>{const submitted=$('#content-text').value;const result=await api('/api/version',{task_id:b.task_id,base_version:savedDraft?savedDraft.base_version:(v?.version_id??null),text:submitted});const currentDraft=draft('content:'+b.task_id),hasLaterEdits=currentDraft&&currentDraft.text!==submitted;if(hasLaterEdits)cache('content:'+b.task_id,{...currentDraft,base_version:latest(result)?.version_id});else clearDraft('content:'+b.task_id);compareVersion=v?.version_id||null;await refresh();toast(hasLaterEdits?'提交的正文已保存；保存期间新增的修改保留在草稿中。':'新版本已保存，旧版保留在“对照旧版”中。')},e.target);
 if($('#adopt-version'))$('#adopt-version').onclick=e=>guard(async()=>{await api('/api/adopt',{task_id:b.task_id,version_id:v.version_id});await refresh();toast('已标记为使用版本，不会自动发布。')},e.target);
 $('#content-ai-message').oninput=e=>cache('revision:'+b.task_id,{text:e.target.value});
 $('#content-ai-form').onsubmit=e=>{e.preventDefault();guard(async()=>{const message=$('#content-ai-message').value.trim();if(!message)throw Error('请写下希望 AI 怎么改，或首稿的具体要求');if($('#content-text').value!==(v?.text||''))throw Error('请先保存正文，再交给 AI 修改');await api('/api/request',{kind:v?'revision':'production',task_id:b.task_id,material_id:b.workbench_source,message});clearDraft('revision:'+b.task_id);await refresh();toast('要求已保存，等待当前 AI 对话处理。')},e.submitter)};
 bindCompanion();
}

let growthTab='overview', selectedReview=null, dataQuery='', dataChannel='all';
const formatName=f=>({article:'文章',answer:'回答',note:'笔记'})[f]||'';
const channelName=c=>({wechat:'公众号',douyin:'抖音',zhihu:'知乎',xiaohongshu:'小红书'})[c]||c;
const metricLabels={voteups:'赞同',reads:'阅读',plays:'播放',likes:'点赞',comments:'评论',shares:'分享',collects:'收藏',follows:'新增关注',average_read_minutes:'平均阅读（分钟）',completion_rate:'完读率',paid_reads:'加热阅读',message_read_rate:'消息阅读率',spend:'消耗（元）',impressions:'展示',clicks:'点击',conversions:'转化',revenue:'收入（元）'};
function growthMetric(k,v){return v==null?'未记录':typeof v==='number'?(k.endsWith('_rate')?(v*100).toFixed(1)+'%':number(v)):txt(v)}
function metricBox(values){return `<dl class="growth-metrics">${Object.entries(values||{}).map(([k,v])=>`<div><dt>${esc(metricLabels[k]||k)}</dt><dd>${esc(growthMetric(k,v))}</dd></div>`).join('')||'<p class="muted">暂无这类数据</p>'}</dl>`}
function activeReview(){return (state.growth?.reviews||[]).find(r=>r.id===selectedReview)||(state.growth?.reviews||[])[0]}
function growthRow(r,review){const d=review?.diagnosis?.items?.find(x=>x.content_id===r.content_id)||{},s=r.snapshots?.at(-1)||{};
 const match=state.productions.find(b=>b.task_id===r.production_ref);
 return `<details class="growth-content" ${(selectedResult===r.content_id)?'open':''}><summary><span><strong>${esc(r.title)}</strong><small>${esc(channelName(r.channel))}${formatName(r.format)?' · '+esc(formatName(r.format)):''} · ${r.published_at?'发布于 '+esc(r.published_at.slice(0,10)):'发布时间未记录'}${r.version_id?' · '+esc(r.version_id):' · 历史作品'}</small></span><span class="growth-row-action">${esc(({continue:'继续',modify:'修改',stop:'停止',validate:'再验证'})[d.decision]||d.action||'数据记录')}</span></summary><div class="growth-content-body">
 ${match?`<button class="text-button" data-task="${esc(match.task_id)}">对照制作内容</button>`:''}${/^https?:\/\//.test(r.content_locator||'')?`<a href="${esc(r.content_locator)}" target="_blank" rel="noreferrer">查看原作品</a>`:''}
 <p class="muted">数据截至 ${esc(s.data_through||'未记录')} · 采集于 ${esc(s.observed_at||'未记录')}</p><h3>内容表现</h3>${metricBox(s.public_metrics)}${Object.keys(s.internal_metrics||{}).length?`<h3>后台或投放数据</h3>${metricBox(s.internal_metrics)}`:''}${Object.keys(s.business_results||{}).length?`<h3>业务结果与反馈</h3>${metricBox(s.business_results)}`:''}
 ${d.facts?.length?`<h3>已经看到</h3>${list(d.facts)}`:''}${d.observations?.length?list(d.observations):''}${d.primary_explanation?`<h3>目前的理解</h3><p>${esc(d.primary_explanation)}</p>`:''}${d.competing_explanations?.length?`<h3>还可能是</h3>${list(d.competing_explanations)}`:''}
 ${d.unknowns?.length?`<p class="muted">还不知道：${esc(d.unknowns.join('；'))}</p>`:''}<details class="growth-sources"><summary>数据来源与历次记录 · ${r.snapshots?.length||0} 次</summary>${(r.snapshots||[]).slice().reverse().map(x=>`<p>${esc(x.observed_at)} · 截至 ${esc(x.data_through||'未记录')}<br>${esc((x.source_refs||[]).join('；'))}</p>`).join('')}</details>${review?`<button class="text-button" data-growth-correct="${esc(r.content_id)}" data-channel="${esc(r.channel)}">补充或纠正这条判断</button>`:`${matchingReview(r)?`<button class="text-button" data-review="${esc(matchingReview(r).id)}">查看相关复盘</button>`:''}<button class="text-button" data-data-correct="${esc(r.content_id)}" data-channel="${esc(r.channel)}">补充或纠正数据</button>`}</div></details>`}
function dataRows(){return(state.ledger?.items||[]).filter(r=>(dataChannel==='all'||r.channel===dataChannel)&&[r.title,r.channel,r.content_id].join(' ').toLowerCase().includes(dataQuery.toLowerCase()))}
function matchingReview(row){return(state.growth?.reviews||[]).find(r=>r.scope?.some(x=>x.channel===row.channel&&x.content_id===row.content_id))}
function rowKey(r){return JSON.stringify([r.channel,r.content_id])}
function metricValue(r,key){const [group,k]=key.split(':');return r.snapshots?.at(-1)?.[group]?.[k]}
function displayedMetrics(rows){return [...new Set(rows.flatMap(r=>{const s=r.snapshots?.at(-1)||{};return ['public_metrics','internal_metrics'].flatMap(g=>Object.keys(s[g]||{}).map(k=>g+':'+k))}))]}
function sortedData(rows){return metricSort?rows.slice().sort((a,b)=>{const x=metricValue(a,metricSort),y=metricValue(b,metricSort);if(x==null||typeof x!=='number')return y==null||typeof y!=='number'?0:1;if(y==null||typeof y!=='number')return-1;return sortAscending?x-y:y-x}):rows}
function dataTable(rows){const available=displayedMetrics(rows),multiPlatform=new Set(rows.map(r=>r.channel)).size>1;const names=(multiPlatform?['public_metrics:reads','public_metrics:voteups','public_metrics:likes','public_metrics:collects','public_metrics:comments',...available].filter((k,i,a)=>available.includes(k)&&a.indexOf(k)===i):available).slice(0,5);
 return `<div class="growth-table-wrap"><table class="growth-table data-table"><thead><tr><th class="compare-cell">对比</th><th>内容</th>${names.map(k=>`<th><button class="sort-button" data-sort="${esc(k)}" aria-label="按${esc(metricLabels[k.split(':')[1]]||k.split(':')[1])}排序">${esc(metricLabels[k.split(':')[1]]||k.split(':')[1])} ${metricSort===k?(sortAscending?'↑':'↓'):'↕'}</button>${k.startsWith('internal')?'<small>后台 / 投放</small>':''}</th>`).join('')}</tr></thead><tbody>${sortedData(rows).map(r=>`<tr class="${selectedResult===r.content_id&&selectedDataChannel===r.channel?'selected':''}"><td class="compare-cell"><input type="checkbox" data-compare-row="${esc(rowKey(r))}" aria-label="对比 ${esc(r.title)}" ${comparedRows.has(rowKey(r))?'checked':''}></td><td><button class="text-button" data-data-detail="${esc(r.content_id)}" data-channel="${esc(r.channel)}">${esc(r.title)}</button><small>${esc(channelName(r.channel))}${formatName(r.format)?' · '+esc(formatName(r.format)):''} · ${r.published_at?esc(r.published_at.slice(0,10)):'发布日期未记录'}</small></td>${names.map(k=>`<td>${esc(growthMetric(k.split(':')[1],metricValue(r,k)))}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function recordInspector(r){
 if(!r)return'<div class="empty-small"><h3>选择一条内容</h3><p>在表格中点击标题，在这里查看数据、来源与相关分析。</p></div>';
 const snapshot=r.snapshots?.at(-1)||{},review=matchingReview(r),d=review?.diagnosis?.items?.find(x=>x.content_id===r.content_id)||{};
 return `<section class="record-inspector"><div class="inspector-heading"><p class="object-meta">${esc(channelName(r.channel))}${formatName(r.format)?' · '+esc(formatName(r.format)):''} · ${r.published_at?esc(r.published_at.slice(0,10)):'发布日期未记录'}</p><h2>${esc(r.title)}</h2>${/^https?:\/\//.test(r.content_locator||'')?`<a href="${esc(r.content_locator)}" target="_blank" rel="noreferrer">查看原作品 ↗</a>`:''}</div><div class="work-tabs"><span>内容表现</span><button class="text-button" data-data-correct="${esc(r.content_id)}" data-channel="${esc(r.channel)}">补充数据</button></div><div class="inspector-body"><p class="panel-hint">数据截至 ${esc(snapshot.data_through||'未记录')} · ${r.snapshots?.length||0} 次记录</p>${metricBox(snapshot.public_metrics)}${snapshot.missing_fields?.length?`<p class="panel-hint">未记录：${esc(snapshot.missing_fields.join('、'))}</p>`:''}${Object.keys(snapshot.internal_metrics||{}).length?`<h3>后台 / 投放</h3>${metricBox(snapshot.internal_metrics)}`:''}${Object.keys(snapshot.business_results||{}).length?`<h3>实际反馈</h3>${metricBox(snapshot.business_results)}`:''}
 ${review?`<section class="inline-diagnosis"><h3>已有分析</h3>${d.facts?.length?list(d.facts):''}<p>${esc(d.primary_explanation||'这条内容已纳入报告，可打开查看。')}</p>${d.unknowns?.length?`<p class="panel-hint">待核实：${esc(d.unknowns.join('；'))}</p>`:''}<p class="panel-hint">依据 ${date(review.created_at)} 的报告，数据可能与当前记录不同。</p><button class="text-button" data-review="${esc(review.id)}">打开相关复盘 ↗</button></section>`:'<p class="panel-hint">尚无相关分析，数据可独立查看。</p>'}
 <details class="growth-sources"><summary>数据来源与历次记录</summary>${(r.snapshots||[]).slice().reverse().map(x=>`<div class="snapshot"><p>${esc(x.observed_at)} · 截至 ${esc(x.data_through||'未记录')}</p>${metricBox({...x.public_metrics,...x.internal_metrics})}<small>${esc((x.source_refs||[]).join('；'))}</small></div>`).join('')}</details></div></section>`;
}
function comparisonHTML(){
 const rows=(state.ledger?.items||[]).filter(r=>comparedRows.has(rowKey(r)));if(rows.length<2)return'';
 const names=displayedMetrics(rows);
 return `<section class="comparison-workspace"><div class="section-heading"><h2>并排对比 · ${rows.length} 条</h2><button class="quiet" data-action="clear-comparison">结束对比</button></div><p class="panel-hint">各列保留自己的平台、发布日期和数据截至日期；范围不同的数值不宜直接判断优劣。</p><div class="growth-table-wrap"><table class="comparison-table"><thead><tr><th>对照项目</th>${rows.map(r=>`<th>${esc(r.title)}<small>${esc(channelName(r.channel))}</small></th>`).join('')}</tr></thead><tbody><tr><th>发布日期</th>${rows.map(r=>`<td>${esc(r.published_at||'未记录')}</td>`).join('')}</tr><tr><th>数据截至</th>${rows.map(r=>`<td>${esc(r.snapshots?.at(-1)?.data_through||'未记录')}</td>`).join('')}</tr>${names.map(k=>`<tr><th>${esc(metricLabels[k.split(':')[1]]||k.split(':')[1])}${k.startsWith('internal')?'<small>后台 / 投放</small>':'<small>公开数据</small>'}</th>${rows.map(r=>`<td>${esc(growthMetric(k.split(':')[1],metricValue(r,k)))}</td>`).join('')}</tr>`).join('')}</tbody></table></div></section>`;
}
function reportPreview(r){return `<button class="report-preview" data-review="${esc(r.id)}"><span><strong>${esc(r.label)}</strong><small>${r.ledger_snapshot?.items?.length||0} 条内容 · ${date(r.created_at)}</small><span class="report-excerpt">${esc(r.diagnosis?.summary||'已保存的复盘报告')}</span></span><span aria-hidden="true">↗</span></button>`}
function reportHTML(review){if(!review)return'<div class="empty"><h2>这里收纳你的复盘报告</h2><p>把已有报告交给 AI 整理，也可以让 AI 根据现有内容和数据作分析。</p><button class="secondary" data-action="growth-analyze">分析已有资料</button></div>';
 const d=review.diagnosis||{},rows=review.ledger_snapshot?.items||[],newer=(state.growth?.reviews||[]).find(r=>r.previous_review_id===review.id);
 return `<article class="report-document"><header class="report-heading"><div><p class="eyebrow">复盘报告 · ${rows.length} 条内容</p><h2>${esc(review.label)}</h2><p class="muted">${date(review.created_at)} · ${esc(review.source_note||'依据保存的资料整理')}</p></div><button class="quiet" data-action="growth-correct">补充或纠正</button></header>${review.stale||newer?`<p class="notice">报告保留了当时的数据与判断。${newer?`已有更新版本。<button class="text-button" data-review="${esc(newer.id)}">查看新版</button>`:'当前资料已有变化，可按需要重新分析。'}</p>`:''}
 <section class="report-conclusion"><h3>${esc(d.summary)}</h3>${list(d.account_review?.conclusions||[])}</section>
 ${d.highlights?.length?`<div class="growth-highlights">${d.highlights.map(h=>`<article><p class="state-label">${esc(h.label)}</p><h3>${esc(h.title)}</h3><p>${esc(h.detail)}</p>${h.content_id?`<button class="text-button" data-report-evidence="${esc(h.content_id)}">查看报告中的依据</button>`:''}</article>`).join('')}</div>`:''}
 ${d.method_findings?.length?`<section class="growth-limits"><h3>内容与做法分析</h3>${list(d.method_findings)}</section>`:''}
 ${d.caveats?.length?`<section class="growth-limits"><h3>数据范围与待核实信息</h3>${list(d.caveats)}</section>`:''}
 <section id="report-evidence"><h3>报告引用的内容与数据</h3><p class="muted">这里保留报告形成时的数据；最新记录可以在“内容明细”查看。</p>${rows.map(r=>growthRow(r,review)).join('')}</section></article>`}
function renderResults(){
 const rows=dataRows(),all=state.ledger?.items||[],reviews=state.growth?.reviews||[],channels=[...new Set(all.map(r=>r.channel))];
 if(screen==='detail'){const row=all.find(r=>r.content_id===selectedResult&&r.channel===selectedDataChannel);$('#workspace').innerHTML=row?backButton('results','返回数据列表')+`<div class="data-detail-page">${recordInspector(row)}</div>`:missingObject('results','返回数据列表');return}
 if(screen==='compare'){$('#workspace').innerHTML=backButton('results','返回数据列表')+(comparisonHTML()||'<div class="empty"><h2>先选择两条或三条作品</h2><p>在数据列表勾选后，再进入对比。</p></div>');return}
 if(screen==='report'){const r=reviews.find(x=>x.id===selectedReview);$('#workspace').innerHTML=r?backButton('results/reports','返回复盘列表')+reportHTML(r):missingObject('results/reports','返回复盘列表');return}
 const adopted=state.productions.some(b=>(b.workbench_versions||[]).some(v=>v.adopted));
 $('#workspace').innerHTML=`<div class="library-intro"><div><h2>${screen==='reports'?'复盘报告':'内容表现'} <small>${screen==='reports'?reviews.length+' 份':all.length+' 条'}</small></h2><p>${screen==='reports'?'选择一份报告，回看当时的判断与依据。':'先看整体表现，选择作品深入查看，或勾选几条比较。'}</p></div><div class="actions"><button class="quiet" data-action="growth-input">导入数据与资料</button><button class="secondary" data-action="growth-analyze">让 AI 分析</button>${adopted?'<button class="quiet" data-action="record-result">添加使用记录</button>':''}</div></div>${pendingLine(queue().filter(r=>['growth_data','growth_review'].includes(r.kind)))}
 <div class="growth-tabs"><button data-route="results" aria-selected="${screen==='library'}">内容表现</button><button data-route="results/reports" aria-selected="${screen==='reports'}">复盘报告</button></div>
 ${screen==='reports'?`<div class="report-list">${reviews.map(reportPreview).join('')||'<div class="empty"><h2>尚未保存报告</h2><p>数据可独立查看，需要时再让 AI 分析。</p></div>'}</div>`:`<div class="data-filters"><label for="data-channel">平台<select id="data-channel"><option value="all">全部平台</option>${channels.map(c=>`<option value="${esc(c)}" ${c===dataChannel?'selected':''}>${esc(channelName(c))}（${(state.ledger?.items||[]).filter(r=>r.channel===c).length}）</option>`).join('')}</select></label><label for="data-search">查找内容<input id="data-search" value="${esc(dataQuery)}" placeholder="按标题查找"></label><div class="compare-control"><span>${comparedRows.size?'已选 '+comparedRows.size+' 条':'勾选 2–3 条对比'}</span><button class="quiet" data-route="results/compare" ${comparedRows.size<2?'disabled':''}>对比数据</button>${comparedRows.size?'<button class="text-button" data-action="clear-comparison">清空</button>':''}</div></div><section class="data-records data-library" aria-label="内容数据表">${rows.length?dataTable(rows):'<div class="empty"><h2>没有匹配的内容记录</h2><p>可以调整筛选，或导入已有资料。</p></div>'}</section>`}`;
 if($('#data-channel'))$('#data-channel').onchange=e=>{dataChannel=e.target.value;persistBrowse();renderResults()};
 if($('#data-search'))$('#data-search').oninput=e=>{dataQuery=e.target.value;persistBrowse();const pos=e.target.selectionStart;renderResults();$('#data-search').focus();$('#data-search').setSelectionRange(pos,pos)};
 $$('[data-compare-row]').forEach(input=>input.onchange=e=>{const k=e.target.dataset.compareRow;if(e.target.checked){if(comparedRows.size>=3){e.target.checked=false;toast('一次最多对比 3 条，请先取消一条。');return}comparedRows.add(k)}else comparedRows.delete(k);persistBrowse();const y=scrollY;renderResults();window.scrollTo(0,y)});
}

function growthDialog(mode='input',contentId=null,channel=null){
 const review=activeReview(),correct=mode==='correct',importOnly=mode==='input';
 const row=contentId?(state.ledger?.items||[]).find(r=>r.content_id===contentId&&(!channel||r.channel===channel)):null;
 const target=row?`关于作品「${row.title}」（平台：${channelName(row.channel)}；channel=${row.channel}；content_id=${row.content_id}）：`:contentId?`关于作品 content_id=${contentId}：`:'';
 const draftKey='growth-message:'+mode+':'+(row?rowKey(row):contentId||'all');
 showDialog(`<h2>${correct?'哪里需要纠正？':importOnly?(row?'补充这条作品的数据':'整理哪些数据与资料？'):'想分析哪些内容？'}</h2>${row?`<div class="target-record"><b>${esc(row.title)}</b><span>${esc(channelName(row.channel))} · ${esc(row.published_at||'发布日期未记录')}</span></div>`:''}<p>${correct?'说出不准确的地方或补充事实，AI 会重看数据并更新判断。':row?'可以填写补充信息，或上传这条作品的数据、截图；作品信息会一起交给 AI。':'给账号主页，或说明已有数据在哪里；也可以直接上传导出、截图或评论资料。'}</p><form id="growth-request"><label for="growth-message">${correct?'你的补充':row?'要补充的数据或说明':'账号或这次想看的内容'}</label><textarea id="growth-message" required placeholder="${correct?'例如：这篇做过加热，需要结合投放数据判断。':row?'例如：这是这篇作品最新的后台截图，阅读量有更新。':'例如：整理这个账号最近的内容和数据。'}">${esc(draft(draftKey)?.text||'')}</textarea><div class="actions"><button class="primary">${correct?'更新这份分析':importOnly?'整理并保存资料':'生成分析报告'}</button>${!correct?'<button type="button" class="quiet" data-action="growth-upload">上传数据或截图</button>':''}</div></form><input id="growth-file" type="file" accept=".csv,.xlsx,.json,.txt,.md,.pdf,.png,.jpg,.jpeg" data-import-only="${importOnly}" data-target="${esc(target)}" data-draft-key="${esc(draftKey)}" hidden>`);
 $('#growth-message').oninput=e=>cache(draftKey,{text:e.target.value});
 $('#growth-request').onsubmit=e=>{e.preventDefault();guard(async()=>{const message=target+$('#growth-message').value;await api(importOnly?'/api/growth-data':'/api/growth-review',{message,review_id:correct?review?.id:null});clearDraft(draftKey);await refresh();resumeDialog(importOnly?'资料整理要求已保存':'分析要求已保存',importOnly?'AI 整理后，数据会出现在总览与明细中。':'分析完成后，报告会保存在复盘报告中。')},e.submitter)};
}
function growthUpload(button){const input=$('#growth-file');input.onchange=()=>guard(async()=>{const file=input.files[0];if(!file)return;const r=await fetch('/api/growth-upload',{method:'POST',headers:{'X-Workbench-Token':$('meta[name="workbench-token"]').content,'X-File-Name':encodeURIComponent(file.name),'X-Review-Message':encodeURIComponent((input.dataset.target||'')+($('#growth-message')?.value||'')),'X-Import-Only':input.dataset.importOnly||'false'},body:file});const data=await r.json();if(!r.ok)throw Error(data.error);clearDraft(input.dataset.draftKey);await refresh();resumeDialog('资料已保存，等待 AI 整理','AI 会连同作品信息核对资料、保留来源。需要分析时，可以单独生成报告。')},button);input.click()}
function manualResultDialog(){
 const adopted=state.productions.flatMap(b=>(b.workbench_versions||[]).filter(v=>v.adopted).map(v=>({b,v,id:b.task_id+':'+v.version_id})));
 const choice=adopted.find(x=>x.id===selectedResult)||adopted.at(-1);if(!choice)return;selectedResult=choice.id;
 showDialog(`<label for="record-select">实际使用的内容</label><select id="record-select">${adopted.map(x=>`<option value="${esc(x.id)}" ${x.id===selectedResult?'selected':''}>${esc(x.v.text.split('\n')[0])} · ${esc(x.v.version_id)}</option>`).join('')}</select>${resultForm(choice)}`);
 $('#record-select').onchange=e=>{selectedResult=e.target.value;manualResultDialog()};
 const form=$('#result-form'),saved=draft('result:'+selectedResult);if(saved)for(const[k,v]of Object.entries(saved))if(form.elements[k])form.elements[k].value=v;
 form.oninput=()=>cache('result:'+selectedResult,Object.fromEntries(new FormData(form)));
 form.onsubmit=e=>{e.preventDefault();guard(async()=>{await api('/api/result',{...Object.fromEntries(new FormData(form)),task_id:choice.b.task_id,version_id:choice.v.version_id});clearDraft('result:'+selectedResult);await refresh();closeDialog();const row=state.ledger.items.find(r=>r.content_id===choice.id);if(row)navigate('results/item/'+encodeURIComponent(row.channel)+'/'+encodeURIComponent(row.content_id));toast('使用记录已保存')},e.submitter)};
}

function resultForm({b,v}){const d=new Date(),today=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;return `<section class="section inline-editor"><h2>给 ${esc(v.version_id)} 添加一次记录</h2><p class="muted">填写实际发生的情况。未知留空；0 只表示实际观察为零。</p><form id="result-form"><div class="two-col"><div class="field-row"><label for="result-source">数据或反馈来自哪里</label><input id="result-source" name="source" required placeholder="例如：投放后台导出 / 课堂人工试读"></div><div class="field-row"><label for="result-date">观察日期</label><input id="result-date" name="observed_at" type="date" required value="${today}"></div></div><div class="two-col"><div class="field-row"><label for="data-through">数据截至哪天（可不填）</label><input id="data-through" name="data_through" type="date"></div></div><div class="field-row"><label for="result-published">实际发布日期（试读尚未发布可留空）</label><input id="result-published" name="published_at" type="date"></div><div class="metric-grid">${[['spend','消耗（元）'],['impressions','展示'],['clicks','点击'],['conversions','转化'],['revenue','收入（元）']].map(([k,l])=>`<div><label for="metric-${k}">${l}</label><input id="metric-${k}" type="number" min="0" step="any" name="${k}" placeholder="未知留空"></div>`).join('')}</div><div class="field-row"><label for="result-note">试用反馈，或同时变化了哪些条件</label><textarea id="result-note" name="note" placeholder="例如：试读时发现开头太长；或者这次更换了受众和预算。"></textarea></div><div class="actions"><button class="primary">保存这次观测</button><button type="button" class="quiet" data-action="close-result-editor">收起，保留未填完的记录</button></div></form></section>`}
const businessFields=[['name','业务名称'],['products','主要产品或服务'],['target_customer','主要服务谁'],['business_goal','当前业务目标'],['claim_boundaries','不能说错的事实或承诺']];
function renderBusiness(){
 const c=state.context||{},sources=state.business_sources||[],missing=businessFields.slice(0,4).filter(([k])=>!txt(c[k]).trim());
 $('#workspace').innerHTML=`<div class="page-tools"><p>企业资料与当前业务理解</p><button class="quiet" data-action="business-help">添加已有资料</button></div>${awaitingContext()?'<div class="request-line"><span>纠正已保存，等待 AI 重新核对素材适配。</span><button class="text-button" data-action="resume">查看处理方式</button></div>':''}
 <div class="business-desk"><section class="business-summary"><div class="section-heading"><h2>${businessEditing?'校正业务理解':'当前业务理解'}</h2>${!businessEditing?'<button class="quiet" data-action="edit-business">修改</button>':''}</div>
 ${businessEditing?`<form id="business-form">${businessFields.map(([k,l])=>`<div class="field-row"><label for="business-${k}">${l}</label>${k==='name'?`<input id="business-${k}" name="${k}" required value="${esc(c[k])}">`:`<textarea id="business-${k}" name="${k}" ${k!=='claim_boundaries'?'required':''}>${esc(txt(c[k]))}</textarea>`}</div>`).join('')}<div class="actions"><button class="primary">保存业务纠正</button><button type="button" class="quiet" data-action="close-business-editor">收起，保留修改</button></div></form>`:`<dl>${businessFields.map(([k,l])=>`<div><dt>${l}</dt><dd>${txt(c[k]).trim()?esc(txt(c[k])):'<span class="missing-fact">尚未整理，待补充</span>'}</dd></div>`).join('')}</dl>${missing.length?`<p class="panel-hint">当前还缺：${missing.map(([,l])=>l).join('、')}。</p>`:''}`}</section>
 <section class="business-source-panel"><h2>资料来源 <small>${sources.length} 份</small></h2><p class="panel-hint">核对理解时，可对照已有资料的来源记录。</p><label class="sr-only" for="business-source-search">查找资料来源</label><input id="business-source-search" value="${esc(businessSourceQuery)}" placeholder="查找资料名称">${sources.length?`<ul>${sources.map(x=>`<li data-source-name="${esc(x.name)}" ${businessSourceQuery&&!x.name.toLowerCase().includes(businessSourceQuery.toLowerCase())?'hidden':''}><strong>${esc(x.name)}</strong><span>${x.available?'原文件在当前项目':'原文件未随此项目带入'}</span><small>${date(x.observed_at)}</small></li>`).join('')}</ul>`:'<p class="empty-small">尚未保存来源记录。将已有资料交给 AI 整理后，会在这里留下引用。</p>'}<button class="text-button" data-action="business-help">交给 AI 整理资料 ↗</button></section></div>`;
 $('#business-source-search').oninput=e=>{businessSourceQuery=e.target.value;$$('[data-source-name]').forEach(el=>el.hidden=!el.dataset.sourceName.toLowerCase().includes(businessSourceQuery.toLowerCase()))};
 if($('#business-form')){const form=$('#business-form'),saved=draft('business');if(saved)for(const[k,v]of Object.entries(saved))if(form.elements[k])form.elements[k].value=v;form.oninput=()=>cache('business',Object.fromEntries(new FormData(form)));form.onsubmit=e=>{e.preventDefault();guard(async()=>{await api('/api/business',Object.fromEntries(new FormData(form)));clearDraft('business');businessEditing=false;await refresh();toast('业务纠正已保存，等待 AI 按新资料核对。')},e.submitter)}}
}
function resumeDialog(title='接着处理已保存的要求',message='回到正在使用的 AI 对话，发送下面这句话。完成后回这里刷新查看结果。'){
 showDialog(`<div class="handoff-receipt"><p class="state-label">要求已保存在当前项目</p><h2>${esc(title)}</h2><p>${esc(message)}</p><div class="resume-steps"><p><b>回 AI 对话</b>让它读取这个工作台，继续处理。</p><p><b>回来看结果</b>处理完成后，点“刷新资料”。</p></div><button class="primary" data-action="copy-resume">复制接续说明</button><p id="copy-status" class="muted">说明会带上当前项目的位置，AI 可以找到同一份任务。</p><button class="text-button" data-action="close-dialog">回工作台</button></div>`)
}
function requestDialog(kind,heading,materialId=null,taskId=null){
 const placeholder={search:'这次想找哪类素材，重点看什么？',analysis:'哪处判断不准确，或还需要看什么证据？',revision:'哪一段需要改，希望变成怎样？'}[kind]||'说清这次要处理什么。';
 showDialog(`<h2>${esc(heading)}</h2><p>要求会和这次的资料一起保存，由 AI 接着处理。</p><form id="request-form"><label for="request-message">这次的具体要求</label><textarea id="request-message" required placeholder="${esc(placeholder)}"></textarea><div class="actions"><button class="primary">保存要求，交给 AI 接续</button></div></form>`);
 $('#request-form').onsubmit=e=>{e.preventDefault();const message=$('#request-message').value;guard(async()=>{await api('/api/request',{kind,message,material_id:materialId,task_id:taskId});await refresh();resumeDialog('要求已保存',message)},e.submitter)};
}
function showRequests(){const sorted=(state.requests||[]).slice().sort((a,b)=>(a.status!=='queued')-(b.status!=='queued')||String(b.created_at).localeCompare(a.created_at));showDialog(`<h2>要求与处理记录</h2>${queue().length?'<div class="actions"><button class="primary" data-action="resume">继续处理已保存的要求</button></div>':''}<div class="request-list">${sorted.map(r=>`<article><p class="state-label">${esc(labels[r.kind]||'业务要求')} · ${r.status==='done'?'已完成':r.status==='needs_review'?'业务已更新，需重新接续':r.status==='failed'?'需要处理':'等待 AI'}</p><h3>${esc(r.message)}</h3>${r.outcome?.summary?`<p>${esc(r.outcome.summary)}</p>`:''}${r.reason?`<p>${esc(r.reason)}</p>`:''}<small>${date(r.created_at)}</small>${r.outcome?.review_id?`<button class="text-button" data-review="${esc(r.outcome.review_id)}">查看复盘</button>`:''}${r.outcome?.task_id?`<button class="text-button" data-task="${esc(r.outcome.task_id)}">查看结果</button>`:''}</article>`).join('')||'<p>还没有保存的要求。</p>'}</div>`)}
async function copy(text){if(navigator.clipboard?.writeText){try{await navigator.clipboard.writeText(text);return}catch{}}const t=document.createElement('textarea');t.value=text;t.style.position='fixed';t.style.opacity='0';document.body.append(t);t.select();const ok=document.execCommand('copy');t.remove();if(!ok)throw Error('浏览器未允许复制，请在 AI 对话中说“继续这个工作台”')}
function startUpload(button){const f=$('#video-file');f.onchange=()=>guard(async()=>{const file=f.files[0];if(!file)return;if(file.size>250*1024*1024)throw Error('视频需小于 250 MB');toast('正在把视频放入当前项目…');const r=await fetch('/api/upload',{method:'POST',headers:{'X-Workbench-Token':$('meta[name="workbench-token"]').content,'X-File-Name':encodeURIComponent(file.name)},body:file});const data=await r.json();if(!r.ok)throw Error(data.error||'未能添加视频');await refresh();resumeDialog('视频已保存，接着完成拆解','原文件已放入当前项目，AI 需要实际查看并拆解后，才会出现完整判断。')},button);f.click()}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;const d=b.dataset;
 if(d.route){navigate(d.route);return}
 if(d.toggleCompanion){toggleCompanion(d.toggleCompanion,!(companionOpen&&companionView===d.toggleCompanion));return}
 if(d.contentFilter){contentFilter=d.contentFilter;persistBrowse();renderContent();return}
 if(d.materialView){materialView=d.materialView;const m=state.materials.find(x=>x.id===selectedMaterial);$('#analysis-pane').innerHTML=materialPane(m);$$('[data-material-view]').forEach(x=>x.setAttribute('aria-pressed',String(x.dataset.materialView===materialView)));bindMaterial();return}
 if(d.seek!==undefined){const video=$('#source-player');if(video){const seek=()=>{video.currentTime=Math.min(Number(d.seek),Number.isFinite(video.duration)?Math.max(0,video.duration-.05):Number(d.seek));toast('已定位到 '+d.seek+' 秒，可播放核对。')};if(video.readyState)seek();else{video.addEventListener('loadedmetadata',seek,{once:true});video.load()}}return}
 if(d.companion){companionView=d.companion;$('#content-companion').innerHTML=companionHTML(task());bindCompanion();return}
 if(d.review){navigate('results/report/'+encodeURIComponent(d.review));return}
 if(d.tab){closeDialog();activate(d.tab);return}
 if(d.material){navigate('materials/'+encodeURIComponent(d.material));return}
 if(d.filter){filter=d.filter;persistBrowse();renderMaterials();return}
 if(d.source){navigate('materials/'+encodeURIComponent(d.source));return}
 if(d.task){closeDialog();goTask(d.task);return}
 if(d.result){const row=state.ledger?.items?.find(r=>r.content_id===d.result);if(row)navigate('results/item/'+encodeURIComponent(row.channel)+'/'+encodeURIComponent(row.content_id));else{selectedResult=d.result;manualResultDialog()}return}
 if(d.correct){requestDialog('analysis','核对这条素材的判断',d.correct);return}
 if(d.start){guard(async()=>{const x=await api('/api/start',{material_id:d.start});await refresh();goTask(x.task_id);if(!latest(x))resumeDialog('制作任务已接住这条素材','企业背景、素材依据和制作要求已经保存，回 AI 对话继续做出首稿。')},b);return}
 if(d.growthTab){navigate(d.growthTab==='reports'?'results/reports':'results');return}
 if(d.dataDetail){navigate('results/item/'+encodeURIComponent(d.channel)+'/'+encodeURIComponent(d.dataDetail));return}
 if(d.sort){sortAscending=metricSort===d.sort?!sortAscending:false;metricSort=d.sort;persistBrowse();renderResults();return}
 if(d.selectReport){navigate('results/report/'+encodeURIComponent(d.selectReport));return}
 if(d.reportEvidence){selectedResult=d.reportEvidence;renderResults();$('#report-evidence').scrollIntoView({block:'start'});return}
 if(d.dataCorrect){growthDialog('input',d.dataCorrect,d.channel);return}
 if(d.growthCorrect){growthDialog('correct',d.growthCorrect,d.channel);return}

 if(d.copyContent){guard(async()=>{await copy($('#content-text')?.value??latest(state.productions.find(x=>x.task_id===d.copyContent))?.text??'');toast('当前正文已复制')},b);return}
 switch(d.action){
 case'show-comparison':navigate('results/compare');break;
 case'clear-material-compare':materialComparisons.clear();persistBrowse();renderMaterials();break;
 case'close-companion':toggleCompanion(null,false);break;
 case'compare-latest':compareVersion=latest(task())?.version_id;toggleCompanion('versions',true);break;
 case'rebase-draft':{const current=task(),saved=draft('content:'+current.task_id);if(saved)cache('content:'+current.task_id,{...saved,base_version:latest(current)?.version_id??null});renderContent();toast('草稿已保留，以最新版本为基线；保存后会形成新版本。');break}
 case'clear-comparison':comparedRows.clear();persistBrowse();if(screen==='compare')navigate('results');else renderResults();break;
 case'growth-input':growthDialog();break;
 case'growth-correct':growthDialog('correct');break;
 case'growth-upload':growthUpload(b);break;
 case'growth-analyze':growthDialog('analysis');break;
 case'content-help':showDialog('<h2>整理已有内容</h2><p>把现有正文或文件交给当前 AI 对话，请它整理到这个项目的内容区，保留原文、来源和版本。</p><button class="primary" data-action="copy-resume">复制项目说明</button><p id="copy-status" class="muted">资料需要在 AI 对话中提供。</p>');break;
 case'new-search':requestDialog('search','这次想找什么素材？');break;
 case'add-video':startUpload(b);break;
 case'requests':showRequests();break;
 case'resume':resumeDialog();break;
 case'copy-resume':guard(async()=>{await copy((state.resume_prompt||'继续这个工作台')+'。先读取随包 SKILL.md 和已保存的请求，处理后把真实产物接回当前任务，不新建一套工作台。');$('#copy-status').textContent='已复制。回到 AI 对话粘贴发送，完成后回来刷新。'},b);break;
 case'close-dialog':closeDialog();break;
 case'edit-content':editing=true;renderContent();$('#content-text')?.focus();break;
 case'leave-editor':editing=false;renderContent();break;
 case'discard-draft':showDialog('<h2>放弃未保存的修改？</h2><p>已保存的版本会保留，这份浏览器草稿会清除。</p><div class="actions"><button class="primary" data-action="confirm-discard">放弃草稿</button><button class="quiet" data-action="close-dialog">保留</button></div>');break;
 case'confirm-discard':clearDraft('content:'+selectedTask);closeDialog();renderContent();break;
 case'record-result':manualResultDialog();break;
 case'close-result-editor':closeDialog();break;
 case'edit-business':businessEditing=true;renderBusiness();$('#business-form').scrollIntoView({block:'start'});break;
 case'close-business-editor':businessEditing=false;renderBusiness();break;
 case'business-help':resumeDialog('把已有资料交给 AI，先整理再校正','将已有业务文档、工作流或作品交给 AI，请它读取后更新当前项目的业务理解和资料来源。你回来只需核对不准确的地方。');break;
 }
});
$('#refresh').onclick=e=>guard(refresh,e.target);$('.close').onclick=closeDialog;
$('#detail').addEventListener('close',()=>{$$('#detail video').forEach(v=>v.pause())});
$('.brand').onclick=e=>{e.preventDefault();activate('materials')};
window.addEventListener('popstate',()=>{rememberView();if(state.project_key)applyRoute()});
window.addEventListener('hashchange',()=>{if((location.hash.slice(1)||'materials')!==activeRoute&&state.project_key){rememberView();applyRoute()}});
window.addEventListener('pagehide',rememberView);
refresh().catch(e=>toast(e.message));
